-- Innovation Management System schema
-- Run as the application owner in SQL*Plus, SQLcl, or SQL Developer.
-- This script is for a fresh schema and drops existing IMS objects.

SET DEFINE OFF;
SET SERVEROUTPUT ON;

BEGIN
  FOR t IN (SELECT table_name FROM user_tables WHERE table_name IN
    ('PROJECT_MEMBER','INNOVATION_PROJECT','ATTACHMENT','EVALUATION','IDEA',
     'INNOVATION_CALL','ADMIN_USER','INNOVATOR','USER_ACCOUNT','DEPARTMENT')) LOOP
    EXECUTE IMMEDIATE 'DROP TABLE ' || t.table_name || ' CASCADE CONSTRAINTS';
  END LOOP;
  FOR s IN (SELECT sequence_name FROM user_sequences WHERE sequence_name IN
    ('DEPT_SEQ','USER_SEQ','INNOVATOR_SEQ','ADMIN_SEQ','CALL_SEQ','IDEA_SEQ',
     'EVAL_SEQ','ATTACH_SEQ','PROJECT_SEQ','MEMBER_SEQ')) LOOP
    EXECUTE IMMEDIATE 'DROP SEQUENCE ' || s.sequence_name;
  END LOOP;
END;
/

CREATE SEQUENCE DEPT_SEQ START WITH 6 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE USER_SEQ START WITH 6 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE INNOVATOR_SEQ START WITH 6 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE ADMIN_SEQ START WITH 6 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE CALL_SEQ START WITH 6 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE IDEA_SEQ START WITH 6 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE EVAL_SEQ START WITH 6 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE ATTACH_SEQ START WITH 6 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE PROJECT_SEQ START WITH 6 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE MEMBER_SEQ START WITH 6 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE TABLE DEPARTMENT (
  DeptID NUMBER(6) NOT NULL,
  DeptName VARCHAR2(60) NOT NULL,
  Description VARCHAR2(200),
  Location VARCHAR2(60),
  CONSTRAINT PK_DEPARTMENT PRIMARY KEY (DeptID)
);

CREATE TABLE USER_ACCOUNT (
  UserID NUMBER(6) NOT NULL,
  Username VARCHAR2(40) NOT NULL,
  PasswordHash VARCHAR2(100) NOT NULL,
  Role VARCHAR2(10) NOT NULL,
  Email VARCHAR2(80),
  Status VARCHAR2(10) DEFAULT 'ACTIVE',
  CONSTRAINT PK_USER_ACCOUNT PRIMARY KEY (UserID),
  CONSTRAINT UQ_USERNAME UNIQUE (Username),
  CONSTRAINT CK_ROLE CHECK (Role IN ('ADMIN','INNOVATOR')),
  CONSTRAINT CK_USER_STATUS CHECK (Status IN ('ACTIVE','INACTIVE'))
);

CREATE TABLE INNOVATOR (
  InnovatorID NUMBER(6) NOT NULL,
  UserID NUMBER(6) NOT NULL,
  DeptID NUMBER(6) NOT NULL,
  Name VARCHAR2(60) NOT NULL,
  Email VARCHAR2(80),
  Phone VARCHAR2(20),
  Expertise VARCHAR2(80),
  DateJoined DATE DEFAULT SYSDATE,
  CONSTRAINT PK_INNOVATOR PRIMARY KEY (InnovatorID),
  CONSTRAINT FK_INNOVATOR_USER FOREIGN KEY (UserID) REFERENCES USER_ACCOUNT(UserID),
  CONSTRAINT FK_INNOVATOR_DEPT FOREIGN KEY (DeptID) REFERENCES DEPARTMENT(DeptID)
);

CREATE TABLE ADMIN_USER (
  AdminID NUMBER(6) NOT NULL,
  UserID NUMBER(6) NOT NULL,
  Name VARCHAR2(60) NOT NULL,
  Email VARCHAR2(80),
  Phone VARCHAR2(20),
  CONSTRAINT PK_ADMIN PRIMARY KEY (AdminID),
  CONSTRAINT FK_ADMIN_USER FOREIGN KEY (UserID) REFERENCES USER_ACCOUNT(UserID)
);

CREATE TABLE INNOVATION_CALL (
  CallID NUMBER(6) NOT NULL,
  AdminID NUMBER(6) NOT NULL,
  Title VARCHAR2(100) NOT NULL,
  Description VARCHAR2(300),
  StartDate DATE NOT NULL,
  EndDate DATE,
  Status VARCHAR2(10) DEFAULT 'OPEN',
  CONSTRAINT PK_CALL PRIMARY KEY (CallID),
  CONSTRAINT FK_CALL_ADMIN FOREIGN KEY (AdminID) REFERENCES ADMIN_USER(AdminID),
  CONSTRAINT CK_CALL_STATUS CHECK (Status IN ('OPEN','CLOSED')),
  CONSTRAINT CK_CALL_DATES CHECK (EndDate IS NULL OR EndDate >= StartDate)
);

CREATE TABLE IDEA (
  IdeaID NUMBER(6) NOT NULL,
  InnovatorID NUMBER(6) NOT NULL,
  DeptID NUMBER(6) NOT NULL,
  CallID NUMBER(6) NOT NULL,
  Title VARCHAR2(100) NOT NULL,
  Description VARCHAR2(400),
  Category VARCHAR2(50),
  SubmissionDate DATE DEFAULT SYSDATE,
  Status VARCHAR2(12) DEFAULT 'PENDING',
  CONSTRAINT PK_IDEA PRIMARY KEY (IdeaID),
  CONSTRAINT FK_IDEA_INNOVATOR FOREIGN KEY (InnovatorID) REFERENCES INNOVATOR(InnovatorID),
  CONSTRAINT FK_IDEA_DEPT FOREIGN KEY (DeptID) REFERENCES DEPARTMENT(DeptID),
  CONSTRAINT FK_IDEA_CALL FOREIGN KEY (CallID) REFERENCES INNOVATION_CALL(CallID),
  CONSTRAINT CK_IDEA_STATUS CHECK (Status IN ('PENDING','APPROVED','ACCEPTED','REJECTED'))
);

CREATE TABLE EVALUATION (
  EvaluationID NUMBER(6) NOT NULL,
  IdeaID NUMBER(6) NOT NULL,
  AdminID NUMBER(6) NOT NULL,
  EvaluationDate DATE DEFAULT SYSDATE,
  Score NUMBER(3) CHECK (Score BETWEEN 0 AND 100),
  Comments VARCHAR2(300),
  DecisionStatus VARCHAR2(12),
  CONSTRAINT PK_EVALUATION PRIMARY KEY (EvaluationID),
  CONSTRAINT FK_EVAL_IDEA FOREIGN KEY (IdeaID) REFERENCES IDEA(IdeaID),
  CONSTRAINT FK_EVAL_ADMIN FOREIGN KEY (AdminID) REFERENCES ADMIN_USER(AdminID),
  CONSTRAINT CK_EVAL_DECISION CHECK (DecisionStatus IN ('APPROVED','REJECTED','REVISE'))
);

CREATE TABLE ATTACHMENT (
  AttachmentID NUMBER(6) NOT NULL,
  IdeaID NUMBER(6) NOT NULL,
  FileName VARCHAR2(120) NOT NULL,
  FileType VARCHAR2(20),
  FileSize NUMBER(10),
  UploadDate DATE DEFAULT SYSDATE,
  FileUrl VARCHAR2(300),
  CONSTRAINT PK_ATTACHMENT PRIMARY KEY (AttachmentID),
  CONSTRAINT FK_ATTACHMENT_IDEA FOREIGN KEY (IdeaID) REFERENCES IDEA(IdeaID)
);

CREATE TABLE INNOVATION_PROJECT (
  ProjectID NUMBER(6) NOT NULL,
  IdeaID NUMBER(6) NOT NULL,
  ProjectTitle VARCHAR2(100) NOT NULL,
  StartDate DATE DEFAULT SYSDATE,
  EndDate DATE,
  Status VARCHAR2(12) DEFAULT 'ONGOING',
  Description VARCHAR2(300),
  CONSTRAINT PK_PROJECT PRIMARY KEY (ProjectID),
  CONSTRAINT FK_PROJECT_IDEA FOREIGN KEY (IdeaID) REFERENCES IDEA(IdeaID),
  CONSTRAINT UQ_PROJECT_IDEA UNIQUE (IdeaID),
  CONSTRAINT CK_PROJECT_STATUS CHECK (Status IN ('ONGOING','COMPLETED'))
);

CREATE TABLE PROJECT_MEMBER (
  MemberID NUMBER(6) NOT NULL,
  ProjectID NUMBER(6) NOT NULL,
  InnovatorID NUMBER(6) NOT NULL,
  Role VARCHAR2(40),
  JoinedDate DATE DEFAULT SYSDATE,
  Status VARCHAR2(10) DEFAULT 'ACTIVE',
  CONSTRAINT PK_MEMBER PRIMARY KEY (MemberID),
  CONSTRAINT FK_MEMBER_PROJECT FOREIGN KEY (ProjectID) REFERENCES INNOVATION_PROJECT(ProjectID),
  CONSTRAINT FK_MEMBER_INNOVATOR FOREIGN KEY (InnovatorID) REFERENCES INNOVATOR(InnovatorID),
  CONSTRAINT UQ_MEMBER_PROJ_INNOV UNIQUE (ProjectID, InnovatorID),
  CONSTRAINT CK_MEMBER_STATUS CHECK (Status IN ('ACTIVE','COMPLETED'))
);

INSERT INTO DEPARTMENT VALUES (1, 'Computer Science', 'Faculty of Science and Technology', 'Building A');
INSERT INTO DEPARTMENT VALUES (2, 'Electrical Engineering', 'Faculty of Engineering', 'Building B');
INSERT INTO DEPARTMENT VALUES (3, 'Business Administration', 'Faculty of Business', 'Building C');
INSERT INTO DEPARTMENT VALUES (4, 'Civil Engineering', 'Faculty of Engineering', 'Building B');
INSERT INTO DEPARTMENT VALUES (5, 'Environmental Science', 'Faculty of Science and Technology', 'Building A');

-- PasswordHash is SHA-256("adminPass"), matching Login.java.
INSERT INTO USER_ACCOUNT VALUES (1, 'admin', 'f40c05434358a62bde28b7991e16f880d059d99adb2c20242cf2db46c197e322', 'ADMIN', 'admin@example.com', 'ACTIVE');
INSERT INTO USER_ACCOUNT VALUES (2, 'a.karim', 'hashed_pw_2', 'INNOVATOR', 'a.karim@example.com', 'ACTIVE');
INSERT INTO INNOVATOR (InnovatorID, UserID, DeptID, Name, Email, Expertise) VALUES (1, 2, 1, 'Ahsan Karim', 'a.karim@example.com', 'Machine Learning');
INSERT INTO ADMIN_USER VALUES (1, 1, 'Administrator', 'admin@example.com', NULL);
INSERT INTO INNOVATION_CALL VALUES (1, 1, 'Initial Innovation Call', 'Default active call', DATE '2026-01-01', NULL, 'OPEN');

COMMIT;

CREATE OR REPLACE PROCEDURE IMS_INIT_APP AS
BEGIN
  NULL;
END;
/

CREATE OR REPLACE PROCEDURE IMS_REGISTER_USER (
  p_username IN VARCHAR2, p_passwordhash IN VARCHAR2, p_email IN VARCHAR2,
  p_name IN VARCHAR2, p_deptid IN NUMBER, p_userid OUT NUMBER, p_innovatorid OUT NUMBER
) AS
BEGIN
  SELECT USER_SEQ.NEXTVAL INTO p_userid FROM DUAL;
  SELECT INNOVATOR_SEQ.NEXTVAL INTO p_innovatorid FROM DUAL;
  INSERT INTO USER_ACCOUNT (UserID, Username, PasswordHash, Role, Email, Status)
  VALUES (p_userid, p_username, p_passwordhash, 'INNOVATOR', p_email, 'ACTIVE');
  INSERT INTO INNOVATOR (InnovatorID, UserID, DeptID, Name, Email, Expertise)
  VALUES (p_innovatorid, p_userid, NVL(p_deptid, (SELECT MIN(DeptID) FROM DEPARTMENT)), p_name, p_email, NULL);
END;
/

CREATE OR REPLACE PROCEDURE IMS_CREATE_PROJECT (
  p_ideaid IN NUMBER, p_title IN VARCHAR2, p_startdate IN DATE,
  p_enddate IN DATE, p_status IN VARCHAR2, p_description IN VARCHAR2,
  p_projectid OUT NUMBER
) AS
BEGIN
  SELECT PROJECT_SEQ.NEXTVAL INTO p_projectid FROM DUAL;
  INSERT INTO INNOVATION_PROJECT (ProjectID, IdeaID, ProjectTitle, StartDate, EndDate, Status, Description)
  VALUES (p_projectid, p_ideaid, p_title, p_startdate, p_enddate, p_status, p_description);
END;
/

CREATE OR REPLACE PROCEDURE IMS_EVALUATE_IDEA (
  p_ideaid IN NUMBER, p_adminid IN NUMBER, p_score IN NUMBER,
  p_comments IN VARCHAR2, p_decision IN VARCHAR2
) AS
BEGIN
  INSERT INTO EVALUATION (EvaluationID, IdeaID, AdminID, EvaluationDate, Score, Comments, DecisionStatus)
  VALUES (EVAL_SEQ.NEXTVAL, p_ideaid, p_adminid, SYSDATE, p_score, p_comments, p_decision);
  UPDATE IDEA SET Status = p_decision WHERE IdeaID = p_ideaid;
END;
/

CREATE OR REPLACE PROCEDURE IMS_ADD_PROJECT_MEMBER (
  p_projectid IN NUMBER, p_innovatorid IN NUMBER
) AS
BEGIN
  INSERT INTO PROJECT_MEMBER (MemberID, ProjectID, InnovatorID, Role, JoinedDate, Status)
  SELECT MEMBER_SEQ.NEXTVAL, p_projectid, p_innovatorid, 'Member', SYSDATE, 'ACTIVE' FROM DUAL
  WHERE NOT EXISTS (SELECT 1 FROM PROJECT_MEMBER WHERE ProjectID = p_projectid AND InnovatorID = p_innovatorid);
END;
/

COMMIT;
